[package]
name = "accounts"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
solana-client = "3.1.1"
solana-commitment-config = "3.1.0"
solana-sdk = "3.0.0"
solana-system-interface = "3.0.0"
spl-token-2022-interface = "2.1.0"
tokio = { version = "1.48.0", features = ["full"] }
