[package]
name = "dust_sweeper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
solana-client = "3.1.4"
solana-commitment-config = "3.1.0"
solana-sdk = "3.0.0"
solana-system-interface = { version = "3.0.0", features = ["bincode"] }
tokio = "1.48.0"
